### PR TITLE
#12 Add image embeddings

### LINKED ISSUE #12: Add image embeddings
- [x] Add image embeddings using [OpenCLIP](https://github.com/mlfoundations/open_clip)

### PR DESCRIPTION
**Pull request by sighmon**
Resolves #12

Let's add image embeddings so that we can get similar works based on their images/videos.

### Acceptance Criteria
- [x] Add image embeddings using [OpenCLIP](https://github.com/mlfoundations/open_clip)

### Relevant design files
* None

### Testing instructions
1. Update your `config.env` to set `REBUILD=true`, `PAGES=10` and XOS to the dev server: `XOS_API_ENDPOINT=http://dev.acmi.net.au:1005/api/` with `AUTH_TOKEN=<your-dev-server-token>`
1. Build the environment: `make build` (it will take a while to download the OpenCLIP model and rebuild the vector database)
1. Search for work images of people wearing hats: http://localhost:8081/images/?text=people+wearing+hats
1. See similar images works: http://localhost:8081/images/?work=image_1110_0.0
1. Search for video frames of people wearing hats: http://localhost:8081/videos/?text=people+wearing+hats
1. See similar video frames works: http://localhost:8081/videos/?work=video_2689_924.0

### CODE REVIEW

**Comment by rubyquaildesign** [comment]
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://dev.acmi.net.au:8082/api/assets/2689/?page_size=10&ordering=id

getting a 404 when trying to access http://localhost:8081/videos/?work=video_2689_924.0

**Comment by sighmon** [comment]
@rubyquaildesign I've updated the instructions to use port `1005` on our dev server, and also linked to a pre-generated embeddings database to save time. It's about 20% of the way through our video collection.

**Comment by rubyquaildesign** [comment]
Screenshot 2024-07-31 at 10 15 22 am
I feel like there's meant to be something here

**Review by rubyquaildesign — CHANGES_REQUESTED** [review]
looks good, just want to display some indication that a particular collection or query is empty instead of just showing a blank screen

**Comment by sighmon** [comment]
@rubyquaildesign Great idea. How does this look?

empty-database-message-v1

**Review by rubyquaildesign — APPROVED** [review]

**Pull request merged**
